import type { Partner, Session, Note } from './types';
export const event = {
  name: 'Partner Convening 2026',
  location: 'Harare',
  dates: '9–11 November 2026',
  expected: 110,
  sessions: 24,
  partners: 38,
};
export const partners: Partner[] = [
  {
    id: 'osf',
    initials: 'OSF',
    name: 'Open Society Foundations',
    region: 'Global',
    category: 'Foundation',
    tags: ['Democracy', 'Human Rights', 'Justice'],
    since: 2018,
    website: 'opensocietyfoundations.org',
    about:
      'Open Society Foundations builds vibrant and tolerant democracies. OAK partnership covers digital rights and justice initiatives across Eastern Europe and Central Asia.',
    contact: 'Maria Schmidt',
    email: 'm.schmidt@osf.org',
  },
  {
    id: 'aca',
    initials: 'ACA',
    name: 'Africa Climate Alliance',
    region: 'Sub-Saharan Africa',
    category: 'NGO',
    tags: ['Climate Justice', 'Youth Advocacy'],
    since: 2020,
    website: 'africaclimatealliance.org',
    about:
      'Connecting communities and advocates working for climate justice across Sub-Saharan Africa.',
    contact: 'Samuel Okafor',
    email: '',
  },
  {
    id: 'nec',
    initials: 'NEC',
    name: 'Nordic Evaluation Centre',
    region: 'Northern Europe',
    category: 'Research',
    tags: ['Evaluation', 'Learning'],
    since: 2021,
    website: 'nordicevaluation.org',
    about:
      'Supporting evaluation and shared learning to strengthen the impact of philanthropic programmes.',
    contact: 'Dr. Ingrid Holm',
    email: '',
  },
  {
    id: 'mrg',
    initials: 'MRG',
    name: 'MENA Rights Group',
    region: 'Middle East & North Africa',
    category: 'NGO',
    tags: ['Human Rights', 'Documentation'],
    since: 2019,
    website: 'menarights.org',
    about: 'Promoting and protecting fundamental rights across the Middle East and North Africa.',
    contact: 'Fatima Zahra Benali',
    email: '',
  },
  {
    id: 'dfi',
    initials: 'DFI',
    name: 'Digital Frontiers Institute',
    region: 'Global / East Africa',
    category: 'Research',
    tags: ['Digital Rights', 'Internet Freedom'],
    since: 2022,
    website: 'digitalfrontiers.org',
    about: 'Building capacity and sharing knowledge on digital rights and internet freedom.',
    contact: 'Li Wei',
    email: '',
  },
  {
    id: 'gal',
    initials: 'GAL',
    name: 'Global Advocacy Lab',
    region: 'Global',
    category: 'NGO',
    tags: ['Communications', 'Campaigns'],
    since: 2023,
    website: 'globaladvocacylab.org',
    about: 'Collaborative approaches to strategic communications and effective advocacy campaigns.',
    contact: 'Rashida Ahmed',
    email: '',
  },
  {
    id: 'sp',
    initials: 'SP',
    name: 'Sciences Po Paris',
    region: 'Western Europe',
    category: 'Academic',
    tags: ['Research', 'Policy'],
    since: 2020,
    website: 'sciencespo.fr',
    about: 'Bringing research and public policy perspectives to collaborative philanthropy.',
    contact: 'Pierre-Alain Dubois',
    email: '',
  },
  {
    id: 'efg',
    initials: 'EFG',
    name: 'Environmental Funders Group',
    region: 'Europe',
    category: 'Network',
    tags: ['Environment', 'Climate'],
    since: 2017,
    website: 'envfunders.eu',
    about: 'A network for funders to exchange learning and coordinate environmental action.',
    contact: 'Event coordination team',
    email: '',
  },
];
export const sessions: Session[] = [
  {
    id: 'welcome',
    day: 1,
    time: '08:00',
    end: '09:00',
    title: 'Registration & Welcome Coffee',
    speaker: '',
    venue: 'Foyer',
    type: 'Break',
    description: '',
  },
  {
    id: 'opening',
    day: 1,
    time: '09:00',
    end: '10:30',
    title: 'Opening Plenary: Pathways to Impact',
    speaker: 'Dr. Helena Moreau · OAK Foundation',
    venue: 'Main Hall A',
    type: 'Plenary',
    featured: true,
    description:
      'Welcome to the OAK Partner Convening. Explore shared priorities, connect across programmes, and discuss pathways to lasting impact.',
  },
  {
    id: 'coffee',
    day: 1,
    time: '10:30',
    end: '10:50',
    title: 'Coffee Break',
    speaker: '',
    venue: 'Foyer',
    type: 'Break',
    description: '',
  },
  {
    id: 'climate',
    day: 1,
    time: '10:50',
    end: '12:00',
    title: 'Thematic Dialogue: Climate Justice & Grantmaking',
    speaker: 'Samuel Okafor · Africa Climate Alliance',
    venue: 'Conference Room B2',
    type: 'Breakout',
    description:
      'An exchange on equitable grantmaking, community-led climate action and youth advocacy.',
  },
  {
    id: 'learning',
    day: 1,
    time: '10:50',
    end: '12:00',
    title: 'Learning Together: Evidence & Impact',
    speaker: 'Dr. Ingrid Holm · Nordic Evaluation Centre',
    venue: 'Workshop Room C',
    type: 'Workshop',
    description:
      'Share evaluation methods and practical approaches to learning across the portfolio.',
  },
  {
    id: 'lunch',
    day: 1,
    time: '12:00',
    end: '13:30',
    title: 'Networking Lunch',
    speaker: '',
    venue: 'Dining Room',
    type: 'Break',
    description: '',
  },
  {
    id: 'rights',
    day: 1,
    time: '13:30',
    end: '14:30',
    title: 'Partner Spotlight: Rights-Based Approaches',
    speaker: 'Fatima Zahra Benali · MENA Rights Group',
    venue: 'Main Hall A',
    type: 'Plenary',
    description:
      'Partner perspectives on putting rights at the centre of programme design and advocacy.',
  },
  {
    id: 'digital',
    day: 1,
    time: '14:45',
    end: '16:00',
    title: 'Digital Rights in Authoritarian Contexts',
    speaker: 'Li Wei · Digital Frontiers Institute',
    venue: 'Conference Room B1',
    type: 'Breakout',
    description: 'Practical collaboration on digital rights in restricted environments.',
  },
  {
    id: 'dinner',
    day: 1,
    time: '18:00',
    end: '20:00',
    title: 'Welcome Reception & Dinner',
    speaker: '',
    venue: 'Rooftop Terrace',
    type: 'Social',
    description: 'Meet fellow partners and continue the day’s conversations.',
  },
  {
    id: 'day2-opening',
    day: 2,
    time: '09:00',
    end: '10:30',
    title: 'Shared Learning Across the Portfolio',
    speaker: 'OAK Foundation',
    venue: 'Main Hall A',
    type: 'Plenary',
    featured: true,
    description: 'A facilitated exchange on shared learning and collaboration.',
  },
  {
    id: 'day2-coffee',
    day: 2,
    time: '10:30',
    end: '11:00',
    title: 'Coffee Break',
    speaker: '',
    venue: 'Foyer',
    type: 'Break',
    description: '',
  },
  {
    id: 'communications',
    day: 2,
    time: '11:00',
    end: '12:00',
    title: 'Strategic Communications Workshop',
    speaker: 'Rashida Ahmed · Global Advocacy Lab',
    venue: 'Workshop Room C',
    type: 'Workshop',
    description: 'Explore adaptive messaging and campaign planning.',
  },
  {
    id: 'day2-lunch',
    day: 2,
    time: '12:00',
    end: '13:30',
    title: 'Networking Lunch',
    speaker: '',
    venue: 'Dining Room',
    type: 'Break',
    description: '',
  },
  {
    id: 'fishbowl',
    day: 2,
    time: '13:30',
    end: '15:00',
    title: 'Fishbowl: Long-Term Philanthropy',
    speaker: 'Pierre-Alain Dubois · Sciences Po Paris',
    venue: 'Main Hall A',
    type: 'Plenary',
    description: 'Discuss longer time horizons, shared learning and systemic change.',
  },
  {
    id: 'collaboration',
    day: 2,
    time: '15:15',
    end: '16:30',
    title: 'Partner Collaboration Labs',
    speaker: 'Convening facilitators',
    venue: 'Conference Room B2',
    type: 'Breakout',
    description: 'Identify shared priorities and potential cross-programme collaborations.',
  },
  {
    id: 'day2-reflections',
    day: 2,
    time: '16:30',
    end: '17:00',
    title: 'Daily Reflections',
    speaker: 'OAK Foundation',
    venue: 'Main Hall A',
    type: 'Plenary',
    description: 'Gather insights and questions from the day.',
  },
  {
    id: 'day2-social',
    day: 2,
    time: '18:00',
    end: '20:00',
    title: 'Partner Networking Evening',
    speaker: '',
    venue: 'Rooftop Terrace',
    type: 'Social',
    description: 'An informal evening with convening partners.',
  },
  {
    id: 'day3-opening',
    day: 3,
    time: '09:00',
    end: '10:00',
    title: 'From Learning to Collective Action',
    speaker: 'OAK Foundation',
    venue: 'Main Hall A',
    type: 'Plenary',
    featured: true,
    description: 'Turn shared insights into practical next steps.',
  },
  {
    id: 'action',
    day: 3,
    time: '10:00',
    end: '11:00',
    title: 'Action Planning Workshop',
    speaker: 'Convening facilitators',
    venue: 'Workshop Room C',
    type: 'Workshop',
    description: 'Build a practical action plan with your peers.',
  },
  {
    id: 'day3-coffee',
    day: 3,
    time: '11:00',
    end: '11:15',
    title: 'Coffee Break',
    speaker: '',
    venue: 'Foyer',
    type: 'Break',
    description: '',
  },
  {
    id: 'commitments',
    day: 3,
    time: '11:15',
    end: '12:00',
    title: 'Partner Commitments & Next Steps',
    speaker: 'Partner representatives',
    venue: 'Main Hall A',
    type: 'Plenary',
    description: 'Share commitments and agree ways to stay connected.',
  },
  {
    id: 'day3-lunch',
    day: 3,
    time: '12:00',
    end: '13:00',
    title: 'Networking Lunch',
    speaker: '',
    venue: 'Dining Room',
    type: 'Break',
    description: '',
  },
  {
    id: 'closing',
    day: 3,
    time: '13:00',
    end: '14:00',
    title: 'Closing Reflections',
    speaker: 'Dr. Helena Moreau · OAK Foundation',
    venue: 'Main Hall A',
    type: 'Plenary',
    description: 'Reflect on the convening and look ahead.',
  },
  {
    id: 'farewell',
    day: 3,
    time: '14:00',
    end: '15:00',
    title: 'Farewell Coffee & Departures',
    speaker: '',
    venue: 'Foyer',
    type: 'Social',
    description: 'Say farewell and exchange contact details.',
  },
];
export const initialNotes: Note[] = [
  {
    id: 'n1',
    name: 'Maria Schmidt',
    organisation: 'Open Society Foundations',
    day: 1,
    time: '14:32',
    text: 'The rights-based approaches session surfaced strong demand for a shared learning platform. OSF will follow up with MENA Rights Group on joint programming opportunities in the Mediterranean region.',
  },
  {
    id: 'n2',
    name: 'James Odhiambo',
    organisation: 'OAK Foundation',
    day: 1,
    time: '16:50',
    text: 'Digital Rights breakout: participants want a working group to share tools for operating in restricted digital environments. Interested orgs: Digital Frontiers, Access Now, EFF.',
  },
  {
    id: 'n3',
    name: 'Awa Diallo',
    organisation: 'Geneva Secretariat',
    day: 2,
    time: '11:15',
    text: 'Strategic communications workshop highly rated. Rashida’s adaptive messaging framework is directly applicable across 60% of the portfolio. Requesting follow-up toolkit.',
  },
  {
    id: 'n4',
    name: 'Pierre-Alain Dubois',
    organisation: 'Sciences Po Paris',
    day: 2,
    time: '15:00',
    text: 'Fishbowl revealed consensus: philanthropy needs to accept longer time horizons (10+ years) and better share learning. Key ask: OAK to publish failure cases alongside success stories.',
  },
];
export const takeaways = [
  'Philanthropy needs to accept 10+ year time horizons for systemic change',
  'Shared learning infrastructure is the most requested resource across the portfolio',
  'Digital rights must be integrated into all programme areas, not siloed',
  'Rights-based framing significantly improves grantee advocacy effectiveness',
  'Peer exchange is rated more valuable than expert-led sessions (92% vs 74%)',
];
export const resources = [
  {
    id: 'opening-presentation',
    name: 'Opening Plenary Presentation',
    detail: 'PDF · 3.2 MB · Day 1',
  },
  {
    id: 'portfolio-overview',
    name: 'OAK Portfolio Overview 2024–26',
    detail: 'PDF · 1.8 MB · Day 2',
  },
  { id: 'action-workbook', name: 'Action Planning Workbook', detail: 'DOCX · 0.9 MB · Day 3' },
  {
    id: 'partner-directory',
    name: 'Partner Contact Directory',
    detail: 'XLSX · 0.4 MB · All Days',
  },
  { id: 'photo-gallery', name: 'Photo Gallery (High Res)', detail: 'ZIP · 184 MB · All Days' },
];
export const initials = (name: string) =>
  name
    .split(' ')
    .filter(Boolean)
    .map((s) => s[0])
    .slice(0, 2)
    .join('')
    .toUpperCase();
